# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 01:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='player',
        ),
        migrations.DeleteModel(
            name='startplayer',
        ),
    ]
