# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=10)),
                ('Hp', models.IntegerField(default=1)),
                ('Mp', models.IntegerField(default=1)),
                ('Charactercard', models.IntegerField(default=0)),
                ('Activecard1', models.IntegerField(default=0)),
                ('Activecard2', models.IntegerField(default=0)),
                ('Activecard3', models.IntegerField(default=0)),
                ('party_number', models.IntegerField(default=0)),
            ],
        ),
    ]
